//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectPro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class comentarios_foro
    {
        public int id_comentario_foro { get; set; }
        public string comentario { get; set; }
        public System.DateTime fecha_comentario { get; set; }
        public int cod_foro { get; set; }
        public string cod_usuario { get; set; }
    
        public virtual foro foro { get; set; }
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
