//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectPro.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_admin_proyectosEntities : DbContext
    {
        public db_admin_proyectosEntities()
            : base("name=db_admin_proyectosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<comentario_por_tarea> comentario_por_tarea { get; set; }
        public virtual DbSet<comentarios_foro> comentarios_foro { get; set; }
        public virtual DbSet<estado> estado { get; set; }
        public virtual DbSet<foro> foro { get; set; }
        public virtual DbSet<historico_tarea> historico_tarea { get; set; }
        public virtual DbSet<proyecto> proyecto { get; set; }
        public virtual DbSet<tarea> tarea { get; set; }
        public virtual DbSet<usuarios_por_proyecto> usuarios_por_proyecto { get; set; }
    }
}
