//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectPro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tarea
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tarea()
        {
            this.comentario_por_tarea = new HashSet<comentario_por_tarea>();
            this.historico_tarea = new HashSet<historico_tarea>();
        }
    
        public int id_tarea { get; set; }
        public string observacion { get; set; }
        public int cod_proyecto { get; set; }
        public short cod_estado { get; set; }
        public string cod_usuarioAsignado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<comentario_por_tarea> comentario_por_tarea { get; set; }
        public virtual estado estado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<historico_tarea> historico_tarea { get; set; }
        public virtual proyecto proyecto { get; set; }
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
